//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Serialize, Deserialize};


#[derive(Clone, Debug, PartialEq, DeriveEntityModel,Serialize, Deserialize, Eq)]
#[sea_orm(table_name = "task")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub task_id: i32,
    pub task_name: String,
    pub description: Option<String>,
    pub status: Option<i32>,
    pub add_up_num: Option<i32>,
    pub day_up_num: Option<i32>,
    pub add_day_num: Option<i32>,
    pub create_date: Option<String>,
    pub last_record_date: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
